# Generated by Django 5.1.7 on 2025-09-14 10:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='شماره کارت')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی کارت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'کارت\u200cهای بانکی',
                'ordering': ['bank_name', 'card_number'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام تگ')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='رنگ تگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='مبلغ')),
                ('purpose', models.CharField(max_length=200, verbose_name='بابت چه کاری')),
                ('depositor', models.CharField(max_length=100, verbose_name='واریز کننده')),
                ('deposit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ واریز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.bankcard', verbose_name='کارت بانکی')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'واریز',
                'verbose_name_plural': 'واریزها',
                'ordering': ['-deposit_date'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='مبلغ')),
                ('purpose', models.CharField(max_length=200, verbose_name='بابت چه کاری')),
                ('withdrawal_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ برداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.bankcard', verbose_name='کارت بانکی')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'برداشت',
                'verbose_name_plural': 'برداشت\u200cها',
                'ordering': ['-withdrawal_date'],
            },
        ),
    ]
